language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
sudo: required
services:
  - docker
env:
  global:
  - OPAMERRLOGLEN=0
  - PACKAGE=capnp
  matrix:
  - DISTRO=debian-9 OCAML_VERSION=4.02.3
  - DISTRO=debian-9 OCAML_VERSION=4.03.0
  - DISTRO=debian-9 OCAML_VERSION=4.04.0
  - DISTRO=debian-9 OCAML_VERSION=4.05.0
